# Generated by Django 2.2.1 on 2019-06-21 09:27

import apps.photo_gallery.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0003_auto_20190529_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_position', models.CharField(choices=[('tl', 'Top-Left'), ('tc', 'Top-Center'), ('tr', 'Top-Right'), ('cl', 'Center-Left'), ('cc', 'Center-Center'), ('cr', 'Center-Right'), ('bl', 'Bottom-Left'), ('bc', 'Bottom-Center'), ('br', 'Bottom-Right')], max_length=2)),
                ('file', models.ImageField(editable=False, upload_to=apps.photo_gallery.models.photo_ads_file_path_func)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('ads_sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_ads', to='photo_gallery.Sponsor')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo_ads', to='photo_gallery.Photo')),
            ],
            options={
                'unique_together': {('photo', 'ads_sponsor', 'ads_position')},
            },
        ),
    ]
