# Generated by Django 2.2.1 on 2019-06-22 08:00

import apps.photo_gallery.models
from django.db import migrations, models
import lastweekend_photos.helpers.utils


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0004_photoads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='preview_file',
            field=models.ImageField(editable=False, storage=lastweekend_photos.helpers.utils.OverwriteFileSystemStorage(), upload_to=apps.photo_gallery.models.photo_preview_file_path_func),
        ),
        migrations.AlterField(
            model_name='photoads',
            name='file',
            field=models.ImageField(editable=False, storage=lastweekend_photos.helpers.utils.OverwriteFileSystemStorage(), upload_to=apps.photo_gallery.models.photo_ads_file_path_func),
        ),
    ]
