# Generated by Django 2.2.1 on 2019-06-22 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0005_auto_20190622_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoads',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_ads', to='photo_gallery.Photo'),
        ),
    ]
